### ISSUE TITLE
API KEY env inconsistent between prompy and python

### ISSUE THREAD

**Issue by lenisha** [microsoft/prompty#121]
Prompy Python code is expectig AZURE_OPENAI_KEY env variable to run.
.prompy file run expects by default AZURE_OPENAI_API_KEY in environment.

Could they be the same across? :)

**Comment by sethjuarez** [comment]
Yeah - this seems dumb to me - let me dig into it a bit more.

**Comment by sethjuarez** [comment]
This is resolved in Prompty v2. There are no more implicit environment variable lookups — all env var references are explicit in the `.prompty` file:

```yaml
model:
  connection:
    kind: key
    endpoint: $`{env:AZURE_OPENAI_ENDPOINT}
    apiKey: $`{env:AZURE_OPENAI_API_KEY}
```

You choose the variable names. The runtime and the extension both use the same `$`{env:VAR}` resolution mechanism, so there's no inconsistency.

- **[Connections](https://prompty.ai/core-concepts/connections/)** — how explicit connection config works
- **[Migration Guide](https://prompty.ai/migration/)** — v1 to v2 property mapping

Docs at https://prompty.ai/
