### ISSUE TITLE
.Net required updates

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/prompty#229]
- [x] Remove `Parameters` and `Response` properties
- [x] Handle old `model_id` and `service_id` properties
- [x] Load model parameters and set as options

Model and service ids
```
---
name: Contoso_Chat_Prompt
description: A classifier assistant
authors:
  - ????
model:  
  api: chat
  configuration:
    type: azure_openai
    azure_deployment: gpt-4o
  parameters:
    model_id: gpt-4o
    temperature: 0.0
    max_tokens: 3000
    top_p: 1.0
    response_format: 
      type: json_object
    
---
system:
You are a classifier agent that should know classify a problem into Easy/Medium/Hard based on the problem description.
your response should be in a json format with the following structure:
{
  "difficulty": "Easy/Medium/Hard"
}

user:
{{question}}
```

Model parameters as options
```
 ---
 name: SomePrompt
 description: This is the description.
 model:
     api: chat
     connection:
         type: azure_openai_beta
     parameters:
         logprobs: true
         top_logprobs: 2
         top_p: 1.0
         user: Bob
         stop_sequences:
           - END
           - COMPLETE
         token_selection_biases:
           1: 2
           3: 4
 ---
 Abc---def
```
