### ISSUE TITLE
Error: 401 No authorisation header found in request when running Prompty against Codespaces Models

### ISSUE THREAD

**Issue by mor10** [microsoft/prompty#55]
I'm running the Github Models Codespace: https://github.com/github/codespaces-models

When using GitHub Models, you call the `https://models.inference.ai.azure.com` endpoint and provide a GitHub token and the model name (see example here: https://github.com/github/codespaces-models/blob/main/samples/python/openai/basic.py)

The Codespace also includes Prompty, so I thought I'd try it out.

In settings.json I've updated `prompty.modelConfigurations` as follows:

```json
       {
            "name": "default",
            "type": "azure_openai",
            "api_version": "2023-12-01-preview",
            "azure_endpoint": "${env:GITHUB_ENDPOINT}",
            "azure_deployment": "gpt-4o",
            "api_key": "${env:GITHUB_TOKEN}"
        },
```

with `GITHUB_ENDPOINT` and `GITHUB_TOKEN` defined in my `.env` file.

My `test.prompty` file looks like this:

```yml
---
name: Basic Prompt
description: A basic prompt that uses the chat API to answer questions
model:
    api: chat
    configuration:
        type: azure_openai
        azure_endpoint: https://models.inference.ai.azure.com
        azure_deployment: gpt-4o
    parameters:
        max_tokens: 128
        temperature: 0.2
inputs:
  question:
    type: string
sample:
  "question": "Who is the most famous person in the world?"
---
system:
You are an AI assistant who helps people find information.
As the assistant, you answer questions briefly, succinctly. 

user:
{{question}}
```

When I run it I get this output:

```
2024-08-03 00:03:03.325 [info] Loading /workspaces/codespaces-models/.env
2024-08-03 00:03:03.326 [info] Calling https://models.inference.ai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-12-01-preview
2024-08-03 00:03:03.638 [error] Error: 401 No authorisation header found in request.
Call Stack: Error: 401 No authorisation header found in request.
    at Function.generate (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:85933:14)
    at AzureOpenAI.makeStatusError (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:86715:21)
    at AzureOpenAI.makeRequest (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:86758:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AzureOpenAIExecutor.invoke (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:93031:18)
    at AzureOpenAIExecutor.call (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:17948:16)
    at _InvokerFactory.call (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:17991:16)
    at execute (/home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:93080:18)
    at /home/codespace/.vscode-remote/extensions/ms-toolsai.prompty-0.1.2024060511/packages/core/out/extension.js:93825:28
```

My guess is this is due to an idiosyncrasy in how the `https://models.inference.ai.azure.com` endpoint works, or misconfiguration on my end. 

Any help appreciated.
