### ISSUE TITLE
Built-in prompt compression

### ISSUE THREAD

**Issue by vincentgiraud** [microsoft/prompty#68]
Optimization being part of prompt design, it'd be great to integrate a tool like [LLMLingua](https://github.com/microsoft/LLMLingua) in the VSC extension.

The prompty file could have a `compression` section:
```
compression:
    rate: 0.55
    target_token: 200
    ...
```
