### ISSUE TITLE
Invalid prompty template. Header and content could not be parsed.

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/prompty#70]
I created a simple prompty template in VS Code and ran it with no problem. When I try to load the same template file into Semantic Kernel in VS2022, I get this exception: "Invalid prompty template. Header and content could not be parsed."

Here is my template:
```
---
name: JokePrompt
description: Generate a funny joke
authors:
  - Mike Yeager
model:
  api: chat
  configuration:
    type: azure_openai
  parameters:
    max_tokens: 1000
    temperature: 0.9
    top_p: 0.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
sample:
  subject: square dancing
  style: monty python
---


user:
# WRITE EXACTLY ONE JOKE or HUMOROUS STORY ABOUT THE SUBJECT BELOW

JOKE MUST BE:
- G RATED
- WORKPLACE/FAMILY SAFE

NO SEXISM, RACISM OR OTHER BIAS/BIGOTRY

BE CREATIVE AND FUNNY. I WANT TO LAUGH.

Incorporate the style suggestion, if provided: '{{style}}'

+++++
{{subject}}
+++++
```

And here is my SK code:
```
var builder = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion(
        "MyChatTest",
        _endpoint,
        _apiKey);

var kernel = builder.Build();

var promptyFile = Path.Combine(Directory.GetCurrentDirectory(), "Prompty", "joke.prompty");

#pragma warning disable SKEXP0040 Suppress this diagnostic to proceed.
            var promptyFunction = kernel.CreateFunctionFromPrompty(promptyFile);
#pragma warning restore SKEXP0040Suppress this diagnostic to proceed.

var result = await kernel.InvokeAsync(promptyFunction, new() { ["subject"] = "fishing", ["style"] = "knock knock" });
Console.WriteLine(result);
```
It blows up on kernel.CreateFunctionFromPrompty()

Any ideas? Thanks in advance.
